#!/usr/bin/env bash
# cluster configure.sh — interactive wizard to set up cluster.toml.
#
# Walks the operator through adding one or more AI nodes (chat_reflection,
# code_tools, general) and writes a clean cluster.toml to $CLUSTER_DIR/cluster.toml.
#
# Configuration via env:
#   CLUSTER_DIR — where clusterctl + cluster.toml live (default: /opt/cluster)
#   CLUSTER_NAME — name of the cluster (default: my-cluster)
#
set -Eeuo pipefail

CLUSTER_DIR="${CLUSTER_DIR:-/opt/cluster}"
CLUSTER_NAME="${CLUSTER_NAME:-my-cluster}"
TOML="$CLUSTER_DIR/cluster.toml"
TEMP_TOML="$(mktemp)"
trap 'rm -f "$TEMP_TOML"' EXIT

mkdir -p "$CLUSTER_DIR"

LOG_PREFIX="[configure]"
log()  { echo "$LOG_PREFIX $*" >&2; }
fail() { echo "$LOG_PREFIX ERROR: $*" >&2; exit 1; }
prompt() { read -rp "$1: " var; echo "$var"; }
confirm() { local ans; read -rp "$1 [y/N]: " ans; [[ "$ans" =~ ^[yY] ]]; }

# === Header =================================================================
cat <<EOF

============================================================
 $LOG_PREFIX cluster configuration wizard
============================================================

This wizard will create $TOML with one or more AI nodes.

For each node, you will be asked for:
  - name          (lowercase, dashes only — e.g. "chat-node")
  - role          (chat_reflection | code_tools | general | master)
  - host          (IP or hostname of the node)
  - port          (TCP port — optional if base_url is provided)
  - protocol      (ollama | lmstudio | openai | hermes | custom)
  - model         (model name as the server reports it)
  - base_url      (optional — full URL overrides host+port)
  - token         (optional — Bearer token for protected nodes)

EOF

# === Routing keywords (fixed block — operator can edit later) =============
cat > "$TEMP_TOML" <<EOF
# Auto-generated by configure.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')
# Edit freely after writing — clusterctl reads it on every ask.

[meta]
name = "$CLUSTER_NAME"
created = "$(date -u +'%Y-%m-%d')"

[routing]
# Terms that route an ask to a code_tools node
code_keywords = [
  "código", "code", "function", "función", "script", "python",
  "javascript", "bash", "shell", "regex", "grep", "git",
  "build", "compile", "test", "fix", "bug", "refactor",
  "implement", "install", "npm", "pip", "package", "import",
  "api", "endpoint", "json", "yaml", "html", "css",
  "astro", "react", "vue", "docker", "deploy",
]
# Terms that route an ask to a chat_reflection node
chat_keywords = [
  "explicá", "explica", "explain", "qué es", "why", "how", "cómo",
  "resumí", "summarize", "reflexión", "analizá", "compara",
  "plan", "estrategia", "filosofía", "concepto",
]
# Pure chitchat — goes to a general node (no load on code/chat specialists)
general_penalty = [
  "hola", "hi", "hello", "buenos días", "buenas tardes",
  "cómo estás", "thanks", "gracias", "ok", "bye",
]

[feedback]
mode_default = "synthesis"
mode_verbose = "verbatim"
synthesis_max_lines = 5

EOF

# === Node collection loop ==================================================
node_count=0
while true; do
  echo
  echo "── Add a node ──"
  if (( node_count > 0 )) && ! confirm "Add another node?"; then
    break
  fi
  if (( node_count == 0 )); then
    name=$(prompt "node name (e.g. chat-node)")
  else
    name=$(prompt "node name")
  fi
  role=$(prompt "role [chat_reflection|code_tools|general|master] (default: general)") || true
  role="${role:-general}"
  host=$(prompt "host (IP or hostname)")
  port=$(prompt "port (optional, leave blank to use base_url)") || true
  protocol=$(prompt "protocol [ollama|lmstudio|openai|hermes|custom] (default: ollama)") || true
  protocol="${protocol:-ollama}"
  model=$(prompt "model name (as the server reports it, e.g. gemma4:12b-mlx)") || true
  base_url=$(prompt "base_url (optional, overrides host+port)") || true
  token=$(prompt "API token (optional, Bearer auth)") || true

  cat >> "$TEMP_TOML" <<EOF
# Node #${node_count}
[[node]]
name = "$name"
role = "$role"
host = "$host"
EOF
  [[ -n "$port"     ]] && echo "port = $port"      >> "$TEMP_TOML"
  [[ -n "$protocol" && "$protocol" != "ollama" ]] && echo "protocol = \"$protocol\"" >> "$TEMP_TOML"
  [[ -n "$model"    ]] && echo "model = \"$model\""  >> "$TEMP_TOML"
  [[ -n "$base_url" ]] && echo "base_url = \"$base_url\"" >> "$TEMP_TOML"
  [[ -n "$token"    ]] && echo "token = \"$token\""  >> "$TEMP_TOML"
  echo "enabled = true"   >> "$TEMP_TOML"
  echo "timeout_s = 120"  >> "$TEMP_TOML"
  echo "" >> "$TEMP_TOML"

  node_count=$((node_count + 1))
done

# === Install the config ===================================================
if [[ -f "$TOML" ]]; then
  if ! confirm "cluster.toml already exists — overwrite?"; then
    log "aborted (existing config left untouched)"
    exit 0
  fi
  cp "$TOML" "$TOML.bak.$(date -u +'%Y%m%dT%H%M%SZ')"
  log "backup of old config: $TOML.bak.*"
fi

mv "$TEMP_TOML" "$TOML"
chmod 600 "$TOML"
log "wrote $TOML with $node_count node(s)"

# === Final check ===========================================================
log "testing clusterctl..."
if "$CLUSTER_DIR/bin/clusterctl" nodes list >/dev/null 2>&1; then
  ok=$($CLUSTER_DIR/bin/clusterctl nodes list | grep -c '"name"' || true)
  log "✓ clusterctl reads config OK ($ok nodes reported)"
else
  warn "clusterctl nodes list returned non-zero (some nodes may be down — check connectivity)"
fi

cat <<EOF

============================================================
 ✓ Configuration complete
============================================================

Next steps:
  - verify:   $CLUSTER_DIR/bin/clusterctl nodes list
  - health:   curl http://127.0.0.1:4321/api/health
  - try:      curl -X POST http://127.0.0.1:4321/api/ask \\
                -H 'Content-Type: application/json' \\
                -d '{"text": "hola"}'

To edit nodes later:
  $CLUSTER_DIR/bin/clusterctl nodes add <name> --host X --model Y --role Z
  $CLUSTER_DIR/bin/clusterctl nodes remove <name>
============================================================
EOF
